### PR TITLE
Fix array syntax in hooks template.

### PR DESCRIPTION
**Pull request by jakobw**
Some mixed JSON and PHP array syntax going on there :)

### CODE REVIEW

**Comment by mooeypoo** [comment]
Actually, PHP 5.4 allows for shorthand array syntax :)

http://php.net/manual/en/migration54.new-features.php

**Comment by jakobw** [comment]
Yes, but it should still be arrows `=>` instead of colons `:` for associative arrays ;)
Should I change this patch to use the shorthand array syntax?

**Comment by mooeypoo** [comment]
D'oh! Yes. Oops. The => should change. The [ ] shouldn't, though. Can you quickly fix it? I was trying to make the array shorthand consistent throughout the code. I'll merge the pull request with the => fix.

Thanks for that.... :+1:

**Comment by jakobw** [comment]
Updated! :)

**Comment by mooeypoo** [comment]
:+1:  Thanks!

**Pull request merged**
